// <auto-generated />
namespace _9meetup_codeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class initial_deploy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_deploy));
        
        string IMigrationMetadata.Id
        {
            get { return "202003312326142_initial_deploy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
